syntax = "proto3";

option java_multiple_files = true;
option java_package = "edu.escuelaing.arsw.ejercicio63";
option java_outer_classname = "MedicalProto";

enum SpecialtyType {
  SPECIALTY_MEDICINE    = 0;
  SPECIALTY_PSYCHOLOGY  = 1;
  SPECIALTY_DENTISTRY   = 2;
}

message Specialty {
  int32         id              = 1;
  SpecialtyType type            = 2;
  string        name            = 3;
  string        description     = 4;
  int32         available_slots = 5;
}

message SpecialtyRequest {
  SpecialtyType type = 1;
}

message SpecialtyResponse {
  bool      found     = 1;
  string    message   = 2;
  Specialty specialty = 3;
}

message AllSpecialtiesRequest {}

message SpecialtyList {
  repeated Specialty specialties = 1;
}

service MedicalService {
  rpc GetSpecialty      (SpecialtyRequest)      returns (SpecialtyResponse);
  rpc GetAllSpecialties (AllSpecialtiesRequest) returns (SpecialtyList);
}